### ISSUE TITLE
Trillium install error

### ISSUE THREAD

**Issue by GrumpyMeow** [jdeath/homeassistant-addons#16]
I just started with a fresh HAOS setup. When starting the Trillium addon, the following error is logged:
```
No USER_UID specified, leaving 1000
No USER_GID specified, leaving 1000
node:internal/fs/utils:347
    throw err;
    ^
Error: EACCES: permission denied, mkdir '/share/trillium'
    at Object.mkdirSync (node:fs:1382:3)
    at getTriliumDataDir (/usr/src/app/src/services/data_dir.js:41:16)
    at Object.<anonymous> (/usr/src/app/src/services/data_dir.js:62:26)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/usr/src/app/src/services/log.js:4:17) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/share/trillium'
}
```

It might even be that the "/share"  directory is not yet created by HomeAssistant.

**Comment by jdeath** [comment]
That is why the documentation says to make the directory yourself. Did that not work?
https://github.com/jdeath/homeassistant-addons/tree/main/trillium#installation

**Comment by GrumpyMeow** [comment]
I did create the folder, but the error remained.
Probably the issue has got something to do with the uid. I will retry soon.

**Comment by forzahog** [comment]
I had to "chmod 2777 /share/trillium" to get it to work.

**Comment by jdeath** [comment]
2777 or 777? I added to documentation.

Perhaps in the future, I will convert it to use the new addons_config/ directory instead of share.

**Comment by forzahog** [comment]
I tried 777 first, but it didn't work. 2777 did the trick.
