### ISSUE TITLE
[wg-easy][14] Addon start not possible

### ISSUE THREAD

**Issue by iHaveAstream** [jdeath/homeassistant-addons#41]
Hi @jdeath 

first and foremost: thanks for your nice work on this.

Unfortunately it doesn't work in my case. I did install your addon as per instructions from here:
https://github.com/adriy-be/homeassistant-addons-jdeath/blob/main/wgeasy/README.md

Also the ```/ssl/wg-easy/``` folder is present. However, after a start attempt of the addon, the log throws:

```
}
WG_HOST: *****************
PASSWORD: 
WG_PORT: 51820
WG_CONFIG_PORT: 51820
WG_DEVICE: eth0
WG_PERSISTENT_KEEPALIVE: 25
WG_DEFAULT_ADDRESS: 10.8.0.x
WG_DEFAULT_DNS: 172.30.32.1
WG_ALLOWED_IPS: 0.0.0.0/0, ::/0
WG_PATH: /ssl/wgeasy/
WG_POST_UP: 
WG_POST_DOWN: 
2024-09-06T10:57:53.151Z Server Listening on http://0.0.0.0:51821
2024-09-06T10:57:53.157Z WireGuard Loading configuration...
$ wg genkey
$ echo ***hidden*** | wg pubkey
2024-09-06T10:57:53.174Z WireGuard Configuration generated.
2024-09-06T10:57:53.175Z WireGuard Config saving...
Error: ENOENT: no such file or directory, open '/ssl/wgeasy/wg0.json'
    at async open (node:internal/fs/promises:639:25)
    at async Object.writeFile (node:internal/fs/promises:1212:14)
    at async WireGuard.__saveConfig (/app/lib/WireGuard.js:124:5)
    at async WireGuard.getConfig (/app/lib/WireGuard.js:70:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/ssl/wgeasy/wg0.json'
}
```
This is my config:
```
WG_HOST: **************
PASSWORD: ""
WG_CONFIG_PORT: "51820"
WG_DEVICE: eth0
WG_PATH: /ssl/wgeasy/
WG_PERSISTENT_KEEPALIVE: "25"
WG_DEFAULT_ADDRESS: 10.8.0.x
WG_DEFAULT_DNS: 172.30.32.1
WG_ALLOWED_IPS: 0.0.0.0/0, ::/0
WG_POST_UP: ""
WG_POST_DOWN: ""
PASSWORD_HASH: *****************************
```
I'm running:
```
OS Version: Home Assistant OS 13.1
Home Assistant Core: 2024.8.3
```
Seems like the addon cannot create ```wg0.conf``` and ```wg0.json``` under ```/ssl/wg-easy/``` for some reason.
Any hint would be appreciated.

Thank you!

**Comment by iHaveAstream** [comment]
Sorry, stupid me!
I had created a folder called ```wg-easy```but had not changed the default config path from ```/ssl/wgeasy/``` to ```/ssl/wg-easy/``` 🤣 

The addon is running now!
