### ISSUE TITLE
add more Clients

### ISSUE THREAD

**Issue by Shannondalebreaux** [jdeath/homeassistant-addons#42]
I am getting this error when I try to add more than one 1 client from the GUI. how do I fix this?

}
$ wg genkey
$ echo ***hidden*** | wg pubkey
$ wg genpsk
[h3] [unhandled] H3Error: Maximum number of clients reached.
    at WireGuard.createClient (/app/lib/WireGuard.js:255:13)
    ... 2 lines matching cause stack trace ...
    at async Server.toNodeHandle (/node_modules/h3/dist/index.cjs:2273:7) {
  cause: Error: Maximum number of clients reached.
      at WireGuard.createClient (/app/lib/WireGuard.js:255:13)
      at async Object.handler (/app/lib/Server.js:196:9)
      at async Object.handler (/node_modules/h3/dist/index.cjs:1982:19)
      at async Server.toNodeHandle (/node_modules/h3/dist/index.cjs:2273:7),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}

**Comment by jdeath** [comment]
I am not having issues. I just added a bunch of clients. Are you on version 14?

I suggest removing everything in \ssl\wgeasy and restarting the addon. Maybe something got messed up. you will lose all your old clients though.

**Comment by Shannondalebreaux** [comment]
yes version 14. I tried deleting it, still no luck. same error.

**Comment by jdeath** [comment]
Not sure. Do a clean start. Delete everything in `\ssl\wgeasy` uninstall the addon, go to addon store, refresh the store (3 dots in top right), and re-install addon.

**Comment by Shannondalebreaux** [comment]
Okay thanks. Have a blessed day,Shannon BreauxProverbs 16:7When people's lives please the LORD,even their enemies are at peace withthem.
-------- Original message --------From: jdeath ***@***.***> Date: 9/8/24  8:59 AM  (GMT-06:00) To: jdeath/homeassistant-addons ***@***.***> Cc: Shannondalebreaux ***@***.***>, Author ***@***.***> Subject: Re: [jdeath/homeassistant-addons] add more Clients (Issue #42) 
Not sure. Do a clean start. Delete everything in \ssl\wgeasy uninstall the addon, go to addon store, refresh the store (3 dots in top right), and re-install addon.
