### ISSUE TITLE
Change Detection - Error on opening UI

### ISSUE THREAD

**Issue by a-r-j-a-n** [jdeath/homeassistant-addons#50]
Getting this error when opening the UI. Same via ingress or ip:port.

Installation was working flawless before. Looks like the detection jobs are running flawlessly as well in the logs.
Any clues why this happens?

`[2024-12-13 07:37:09,276] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/changedetectionio/flask_app.py", line 234, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/changedetectionio/flask_app.py", line 493, in index
    output = render_template(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/changedetectionio/templates/watch-overview.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/app/changedetectionio/templates/base.html", line 226, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/changedetectionio/templates/watch-overview.html", line 181, in block 'content'
    <td class="last-changed" data-timestamp="{{ watch.last_changed }}">{% if watch.history_n >=2 and watch.last_changed >0 %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/changedetectionio/model/Watch.py", line 160, in last_changed
    return int(self.__newest_history_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
`

**Comment by jdeath** [comment]
Sorry, I do not actually use it. Let me know if it doesn't resolve. Probably an issue in the actual container.
